### ISSUE TITLE
No significant contacts called from Test Data

### ISSUE THREAD

**Issue by zyqfrog10** [ay-lab/FitHiChIP#11]
Hi,

I am testing FitHiChIP. I couldn't get significant interactions on the provided test data. Is that expected? Thanks.

-Y.Z

**Comment by ay-lab** [comment]
Hi Y Zhan,
Thanks for your comment and for using FitHiChIP. Are you using the most recent code?  Can you please paste / e-mail the console log generated, configuration file parameters, etc? May be due to some missing packages. If you send us the console logs, we can debug it.

**Comment by zyqfrog10** [comment]
Hi,
Thanks for quick reply! 
It looks like the file *PREFIX*.interactions_FitHiC.bed was not generated.

The Parameters.txt:
```
Summarizing the parameters employed in this execution
Listing the input files: 
Input file containing the valid pairs (generated from HIC-PRO pipeline): /data/cer/shared/software/FitHiChIP-7.0/TestData/Sample_ValidPairs.txt.gz 
Input ChIP-seq peak file: /data/cer/shared/software/FitHiChIP-7.0/TestData/Sample.Peaks.gz 
File containing chromosome size information corresponding to the reference chromosome: /data/cer/shared/software/FitHiChIP-7.0/TestData/chrom_hg19.sizes 
Output directory which will store all the results: /data/cer/shared/software/FitHiChIP-7.0/TestData/results 
Base directory containing the HIC-PRO executable: /data/cer/shared/software/HiC-Pro_2.10.0/ 
Low distance threshold: 20000 
Higher distance threshold: 2000000 
BIN_SIZE: 5000 
PREFIX (string of output files): FitHiChIP 
OverWrite (1 means existing files will be overwritten): 1
```
I didn't save the console log for the test data. But I've a log for my other test, which I am attaching here. There is an error in FitHiChIP_HiCPro.sh at line 836.
[FitHiChIP.SRR3467180.log](https://github.com/ay-lab/FitHiChIP/files/3237763/FitHiChIP.SRR3467180.log)

Thanks.
Y.Z.

**Comment by ay-lab** [comment]
Hi @zyqfrog10 

The error reported in line 836 is not critical. I'll fix it in the next release. But please check the following errors:

Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  : 
unable to start device PNG
Calls: ggsave -> dev -> <Anonymous>

Did you solve this problem by checking image rendering in .png format in your machine? If so, and still there is no interaction, please re-run the test once and send me the updated console log.

**Comment by zyqfrog10** [comment]
Hi @ay-lab ,

Looks like it ran through. I added a line ```options(bitmapType = 'cairo', device = 'png')``` prior ggsave. 
Please check out the summary html. Does it look right? 
[FitHiChIP summary Report.pdf](https://github.com/ay-lab/FitHiChIP/files/3238754/FitHiChIP.summary.Report.pdf)

BTW, I didn't find NormFeatures/Coverage_Bias/Plots_Bias/. Is it eliminated in this FitHiChIP release or is there anything wrong in the process?
Parameter and console log are also attached.
[Parameters.txt](https://github.com/ay-lab/FitHiChIP/files/3238760/Parameters.txt)
[TestData.log](https://github.com/ay-lab/FitHiChIP/files/3238761/TestData.log)

Thanks a lot,
Y.Z.

**Comment by ay-lab** [comment]
Yes the summary file and parameters are all OK. Glad to know everything is running. One thing to mention that the plots (within Plots_Bias directory) are now disabled, since those were not directly related to interaction calling. All of those supporting stuffs (and corresponding parameters) are now disabled for making it more user-friendly.

For any queries or errors, please feel free to contact us.
