### ISSUE TITLE
Docker run `bc: command not found`.

### ISSUE THREAD

**Issue by tiagochst** [ay-lab/FitHiChIP#18]
Hello,

I am using the `FitHiChIP_Docker.sh`. I am still interpreting the output. But I got the following eror  during the run `bc: command not found`. Would that be a problem ?

<img width="471" alt="Screen Shot 2019-08-05 at 4 03 36 PM" src="https://user-images.githubusercontent.com/145529/62488436-a99d0f80-b79a-11e9-9e3b-acffec42fb64.png">

I added the log here: https://gist.github.com/tiagochst/61d51afb94af36173e72eb2d9b4b4880

**Comment by tuvangezer** [comment]
Hello,
It seems we didn't have that tool installed in docker image. I've updated the docker image to include it. Please update the image with `docker pull aylab/fithichip` and it should work.
Thanks

**Comment by tiagochst** [comment]
Thanks!
