### ISSUE TITLE
DiffAnalysisHiChIP.r  - Scaling ChIP coverage - scaling_factor : NA 

### ISSUE THREAD

**Issue by jonasungerback** [ay-lab/FitHiChIP#19]
Hello,
Brief explanation: I have no replicates at the moment but I want to compare two conditions. The input files I use are the full interaction files per condition and for --ChIPAlignFileList I use two standard bam-files for my ChIP-sample that have been aligned with bowtie2 and sorted and indexed with samtools. However, early in the process I get the following error that I fail to troubleshoot:
#############################################################
===>> Merging ChIP coverage - processing ChIP-seq alignment file : /path-to-files//WT_rep1_2.s.bam ====>>
===>> Merging ChIP coverage - processing ChIP-seq alignment file : path-to-files//EKO_rep1_2.s.bam ====>>
Killed
===>> Scaling ChIP coverage - scaling_factor : NA ====>>
rm: cannot remove './/ChIP_Coverage_temp2.bed': No such file or directory
*** Performed scaling of ChIP coverage values for uniform ChIP coverage ***
===>>> GroupDistrVec : WT
===>>> GroupDistrVec : EKO Error in DGEList(counts = CountData, group = GroupDistrVec) :
The count matrix is a data.frame instead of a matrix and the first 2 columns are non-numeric.
Should these columns be entered as annotation instead of as counts?
Calls: ApplyEdgeR -> DGEList
Execution halted`
###########################################################
This is the command I am using:

`Rscript /path-to-FitHiChIP/DiffAnalysisHiChIP.r --AllLoopList /path-to-interaction-file_1/FitHiChIP_Peak2ALL_b5000_L10000_U3000000/P2PBckgr_0/Coverage_Bias/FitHiC_BiasCorr/WT_5kb.interactions_FitHiC.bed,/path-to-interaction-file_2/FitHiChIP_Peak2ALL_b5000_L10000_U3000000/P2PBckgr_0/Coverage_Bias/FitHiC_BiasCorr/EKO.interactions_FitHiC.bed --ChrSizeFile /path-chrom-size-file/mm10_chrNameLength.txt --FDRThr 0.05 --OutDir ./ --ChIPAlignFileList /path-to-bam-files/WT_rep1_2.s.bam, /path-to-bam-files/EKO_rep1_2.s.bam --CategoryList WT,EKO`

Thank you in advance!
Jonas

**Comment by jonasungerback** [comment]
I may have figured this one out myself. My initial ChIP-bam files were not paired-end sequenced but when I used two "unrelated" paired.end files it did.

Follow-up question: I do not completely understand the calculations going on here and maybe exact fragment size is crucial, but is it possible to support single-end bam or even bed files as inputs for `--ChIPAlignFileList`?

**Comment by ay-lab** [comment]
Hi Jonas,
Thanks for your query. I use the following two commands on a ChIP BAM file:
1) bedtools makewindows -g _chrsizefile_ -w _binsize_ > _TargetBinnedChrFile_
to first create binned chromosome interval file
2) bedtools coverage -a _TargetBinnedChrFile_ -b _Inp_ChIP.bam_ -counts > _ChIPCovFile_
to create ChIP-seq coverage information from the input alignment file, subject to the specified bin size (equal to the bin size employed in FitHiChIP loops).

Please check if the above mentioned commands work on your single end ChIP BAM files. Your log file says that coverage computation was "killed" midway. Please check if these commands work.

I'll definitely add an option of input ChIP-seq coverage as a bed file in the coming release.

**Comment by jonasungerback** [comment]
Thank you! Those steps seem to work fine so that is most likely not the issue here.

**Comment by jonasungerback** [comment]
Just a quick update for others that may run into the same error:

The problem is definitively on the user end and seems to be triggered when one bam-file is much larger. If I downsample it `(samtools view -s)` to roughly the same size (or a little bigger) it runs fine. I am still not sure why this is the case, if it is something in the code or underlying tools. It could of course be corrupt reads in the bam file as well that disappears in the downsampling but I have done it many times and it always seems to solve the problem.
