### ISSUE TITLE
Error in library(optparse) : there is no package called ‘optparse’

### ISSUE THREAD

**Issue by lishuai800** [ay-lab/FitHiChIP#20]
Hello
I was reported this error when I test the software. but the optparse for python was installed. one of my colleagues suggested that I should also install the package in R which I did not install this package in my conda py27 environment. After the install of all required package in R, all is going well.

**Comment by ay-lab** [comment]
Hi Li Shuai,
Thanks for your query. Yes, the package "optparse" needs to be installed for R as well. Please check the documentation https://ay-lab.github.io/FitHiChIP/usage/installation.html. Please let me know for any problems.
