### ISSUE TITLE
Error with DiffAnalysisHiChIP

### ISSUE THREAD

**Issue by Politropos** [ay-lab/FitHiChIP#23]
Hello
I have run FitHiChiP for two conditions and now I am trying to deduce differential loops 
The command I am using is 
Imp_Scripts/DiffAnalysisHiChIP_Script.sh --AllLoopsList FitHiChIP_WT851A1.1.interactions_FitHiC.bed,FitHiChIPIKDN8512A1.1.interactions_FitHiC.bed --ChrSizeFile chrom_mm10.sizes –-FDRThr 0.01 –-CovThr 25 —-ChIPAlignFileList WT_PreB_851_H3K27Ac_R1.bam,IkDN_PreB_852_H3K27ac_R1.bam –-OutDir /DiffloopsHICHIPpreB1 —-CategoryList WTpreB,IKDNpreB 

I am getting the following error 
Error in parse_args(opt_parser) : 
  Error in getopt(spec = spec, opt = args) : 
  long flag "FDRThrLoop" is invalid
Execution halted

The Chip-Seq bam files are single paired from an independent experiment.
I am not sure if this is the problem 
Thank you

**Comment by ay-lab** [comment]
Hi @Politropos 
I think you already resolved the issue. Should be regarding some parameter specifications. I am closing the issue. If you face any problem, please re-open it.
