### ISSUE TITLE
Simulating HICHIP 

### ISSUE THREAD

**Issue by Politropos** [ay-lab/FitHiChIP#24]
Hello
I would like to run a simulation of  HIC data with H3K27Ac Chip-Seq from the same cells as a comparison to HICHIP data from the same cells as you did in your paper describing the FITHICHIP method. Can I do that with the straight HIC-pro and CHIPseq data sets ?
Reading your manuscript I see is that you pre-selected the interaction matrix  with the help of the CHIP-seq data set. If so is there a method-code  you could share.
Thank you

**Comment by ay-lab** [comment]
Hi @Politropos 
Thanks for posting this issue. Please wait a few days, while I can test and upload the simulation code and its README in the next release. One thing to note that the simulation has a lot of scope for improvement. It was developed primarily for testing the robustness of FitHiChIP, and we found the simulation shows considerable bias in reporting short range (< 100 Kb) interactions. I'll report it in the released code as well, and you are most welcome to check and suggest any possible improvements.

**Comment by ay-lab** [comment]
Hi @Politropos

I hope you have already checked the latest issues with description of simulating HiChIP data. I am closing this issue now. Please get back to me for any problems.

**Comment by Politropos** [comment]
I have
Thank you.
