### ISSUE TITLE
HiC-Pro FitHiChIP issue

### ISSUE THREAD

**Issue by ay-lab** [ay-lab/FitHiChIP#26]
Attaching one issue encountered by Dr. Ricardo N. Ramirez, Harvard Medical School, Boston, MA
****************************************************************************************************
Hi,
I am having issues with the HiCPro component of FitHichip.
I have HiCpro (2.11) installed in my python environment and can run HiC-Pro outside of FitHichip, but still get the flag below?
Do i need to edit the FitHiChIP_HiCPro.sh to point to HiC-Pro??
Here is my log when i run the sample_script.
 ================ Verifying input configuration parameters =================
***** Specified output directory : ./TestData/results/
ERROR ====>>> HiC-pro is not installed in the system !!! FitHiChIP quits !!!
ERROR ====>>> HiC-pro should have version >=  2.9.0 !!! FitHiChIP quits !!!
*** Valid python version is detected - installed version: 2.7.12
*** Python library gzip is installed
*** Python module OptionParser (from the package optparse) is installed
*** Python package networkx is installed
*** Found MACS2 package (for peak calling) installed in the system -  line
*** Valid R version is detected - installed R version: 3.5.1
*** Valid samtools version is detected - installed version: 1.9
*** bgzip utility is installed in the system
*** tabix utility is installed in the system
*** Valid bedtools version is detected - installed version: 2.27.1
 --------->>>>>> ERROR - current system has one or more packages missing
 ------- please check the above logs and install the missing packages before executing FitHiChIP
 ------- exiting for the moment !!
Here: is my bash script for running the sample_test.sh:

#!/bin/bash
#SBATCH -N 1
#SBATCH -c 16                        # number of tasks in job
#SBATCH -p medium                   # queue name
#SBATCH -t 3-00:00                # wall-clock time (hrs:mins)
#SBATCH --mem-per-cpu=4000
#SBATCH -o sampletest.out             # output file name in which %J is replaced by the job ID
#SBATCH -e sampletest.err             # error file name in which %J is replaced by the job ID
module load gcc/6.2.0 bowtie2/2.2.9 python/2.7.12 samtools/0.1.19 R/3.5.1 bedtools samtools/1.9 htslib/1.9.0
source /home/rr190/virtpython-2.7.12/bin/activate
export R_LIBS_USER="~/R-VersionSelected/library"
    # executing FitHiChIP according to the settings of configuration file 
    # any modification of input parameters should be done via the configuration file 
    # executing FitHiChIP(L) with coverage bias regression
bash FitHiChIP_HiCPro.sh -C configfile_BiasCorrection_CoverageBias
    # executing FitHiChIP(L) with ICE bias regression
bash FitHiChIP_HiCPro.sh -C configfile_BiasCorrection_ICEBias
    # executing FitHiChIP(S) with coverage bias regression
bash FitHiChIP_HiCPro.sh -C configfile_P2P_BiasCorrection_CoverageBias
    # executing FitHiChIP(S) with ICE bias regression
bash FitHiChIP_HiCPro.sh -C configfile_P2P_BiasCorrection_ICEBias

Any help would be appreciated,
Thank you.

Ricardo N. Ramirez, Ph.D.
Postdoctoral fellow in the Department of Immunology, Harvard Medical School, Boston, MA

**Comment by ay-lab** [comment]
Hi Dr. Ricardo,
Thanks for your query. I hope you are using the latest code (last updated two days ago). Can you please check the following command inside your bash or qsub environment?
HiC-Pro -v
Or, more specifically,
HiC-Pro -v | head -n 1 | awk -F[" "] '{print $3}' -

If HiC-pro is installed, a version information should be provided as output. Please check.

**Comment by rnr-HMS** [comment]
Hi Dr. Bhattacharyya,
I included the following checks:

/home/rr190/bin/HiC-Pro_2.11.1/bin/HiC-Pro -v
/home/rr190/bin/HiC-Pro_2.11.1/bin/HiC-Pro -v | head -n 1 | awk -F[" "] '{print $3}' -
HiC-Pro version 2.11.1
2.11.1

I also edited my FitHicHIP_Hicpro.sh as indicated below, not sure if this is correct:
#=========================
# check whether HiC-pro is installed or not
#=========================
# path of HiC pro executable
# of the format somedir/bin/HiC-Pro
HiCProExec=_/home/rr190/bin/HiC-Pro_2.11.1/bin/HiC-Pro_

Thanks!

**Comment by rnr-HMS** [comment]
Hi, 
Where do i add the Hic-Pro binary path to $PATH for FitHiChip to work?
I have installed Hic-Pro, just not sure where to point to it for FitHiChIP to recognize it.
Thanks

**Comment by rnr-HMS** [comment]
Hi,
I had to change the config install path to point to the binary. Should maybe include in the installation. Thank you and you can close this issue.

**Comment by ay-lab** [comment]
Hi @rnr-HMS ,
Thanks for your query. You may add your HiC-pro installation in your ~/.bashrc using this template command:
export PATH="......../HiC-Pro_2.11.1/bin/":$PATH 

The latest code (updated 4 days ago) does not require specifying any HiC-pro directory in the configuration file. FitHiChIP will find the HiC-pro executable if it is loaded in the system path. Please try and check if it is useful.

**Comment by rnr-HMS** [comment]
Hi,
I still am having issues where i see a fatal error shown below:
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  : 
  unable to start device PNG
Calls: ggsave -> dev -> <Anonymous>
In addition: Warning message:
In grDevices::png(..., res = dpi, units = "in") :
  unable to open connection to X11 display ''
Execution halted
awk: fatal: cannot open file `/n/groups/cbdm_lab/rr190/FitHiChIP/TestData/H3ktest/FitHiChIP_Peak2NonPeak_b2500_L10000_U10000000/Coverage_Bias/FitHiC_BiasCorr/H3k.interactions_FitH
iC.bed' for reading (No such file or directory)
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  : 
  unable to start device PNG
Calls: ggsave -> dev -> <Anonymous>
In addition: Warning message:
In grDevices::png(..., res = dpi, units = "in") :
  unable to open connection to X11 display ''
Execution halted
awk: fatal: cannot open file `/n/groups/cbdm_lab/rr190/FitHiChIP/TestData/H3ktest/FitHiChIP_Peak2ALL_b2500_L10000_U10000000/P2PBckgr_0/Coverage_Bias/FitHiC_BiasCorr/H3k.interactio
ns_FitHiC.bed' for reading (No such file or directory)

Looks like i never generate the H3k.interactions_FitHiC.bed file. Not sure where things are going awry. Any advice would be appreciated.
Thanks

**Comment by ay-lab** [comment]
Hi @rnr-HMS 
Thanks for your query. Please check the package ggplot2 and corresponding graphics in your machine. You may use the following R script to check if ggplot2 and saving file in .png works in your machine. Otherwise, you please mail me the complete output log.

library(ggplot2)
ggplot(mtcars, aes(mpg, wt)) + geom_point()
ggsave("mtcars.pdf")
ggsave("mtcars.png”)

pdf("test_ggplot.pdf")
ggplot(mtcars, aes(mpg, wt)) + geom_point()
dev.off()
