### ISSUE TITLE
InferPeakHiChIP recovered very few peaks

### ISSUE THREAD

**Issue by emarti88** [ay-lab/FitHiChIP#29]
Hello,

After trying to generate my own peak file with the InferPeakHiChIP.sh utility, the output files are very small.

-rw-rw----+ 1 ... 1.2K Nov 25 16:04 out_macs2_peaks.narrowPeak
-rw-rw----+ 1 ... 2.5K Nov 25 16:04 out_macs2_peaks.xls
-rw-rw----+ 1 ... 807 Nov 25 16:04 out_macs2_summits.bed

I don't know if it is using all the pairs in the HiCPro output file or only using 1.

When printing the referenced RE,SC, and DE files it only references 1 instead of all of them. And it only prints one valid pairs file instead of the allValidPairs file.

Please advise and thank you.
Eduardo

**Comment by ay-lab** [comment]
Hi @emarti88 
Sorry for a delayed response. Is your problem solved? Otherwise, can you please send me the exact command line syntax you are using for InferPeakHiChIP.sh?
