### ISSUE TITLE
Interaction IDs to trace interactions to the original files

### ISSUE THREAD

**Issue by sanchari24** [ay-lab/FitHiChIP#31]
It will be helpful if we get a pair of interaction IDs in the final differential analysis with which we can trace back to the original interaction files (bed files) of the two categories (FitHiChIP.interactions_FitHiC files)

**Comment by ay-lab** [comment]
Hi, one quick fix for this is to simply create an "interaction ID" using
the first few fields of each entry which would be unique (e.g.,
chr1-55000-chr1-125000). You can do that with a simple awk command. Thank
you.
