### ISSUE TITLE
Differential contacts over merged loops?

### ISSUE THREAD

**Issue by DoaneAS** [ay-lab/FitHiChIP#33]
Hi,

Thanks a lot for FitHiChIP, it's very useful for us.

I was wondering if you could advise on how to look at differential loops using the merged significant loops from FitHiChIP output.  I think this was possible in a pervious version of the differential script? (The merging step maybe after computing the differential).  

Also, does the differential script run EdgeR analysis across all pairs of anchors (most of which would not be called loops), or does it consider only the called loops (FitHiChIP significant in at least one rep)?  It looks as though it may be the former, and wonder if you can provide a rational for doing it this way?

thanks,
Ashley

**Comment by ay-lab** [comment]
Hi @DoaneAS 
Thanks for your query. Let me answer the second part first. In fact, not all pairs of anchors, the implementation rather uses all pairs of contacts (having nonzero contact counts) which may or may not be significant in any sample. Union of all contacts in all input samples generate the background of EdgeR. Once differential loops are obtained from EdgeR, we further filter and extract those loops which are significant in at least one replicate is done as a post-processing step. 
The idea is, as the contact count is used as a differential measure, we do not pre-filter contacts based on their significance. Rather, the filtering is done in terms of differential analysis of 1D bins, i.e. contacts involving non-differential 1D bins are only considered.
For the first part, you can overlap between the differential loops and the loops generated by merged filtering. Using only the merged filtering generated loops (which are by definition the most stringent ones within the defined neighborhood) as a background in EdgeR may miss many potential differential loops involving non-differential 1D bins, thus is not recommended.
