### ISSUE TITLE
samtools 1.10 is less than 1.6. 

### ISSUE THREAD

**Issue by jaavedm** [ay-lab/FitHiChIP#34]
I am using FitHiChIP_HiCPro.sh. 
I have samtools 1.10 installed. 
FitHiChip fails to correctly identify this newer version. The error message I get is:

```
ERROR ====>>> Invalid samtools version : 1.10
 - should be at least 1.6 !!! FitHiChIP quits !!!
```

This is the code this is buggy:
```
parsedsamtoolsVersion=$(echo "${samtoolsversion//./}")
if [[ ${samtoolsversion:0:1} == "0" ]]; then
        # samtools version is 0.*
        echo "ERROR ====>>> Invalid samtools version : "$samtoolsversion
        echo " - should be at least 1.6 !!! FitHiChIP quits !!!"
        errcond=1
elif [[ "$parsedsamtoolsVersion" -ge "16" && "$parsedsamtoolsVersion" -lt "99" ]]; then
    echo "*** Valid samtools version is detected - installed version: "$samtoolsversion
elif [[ "$parsedsamtoolsVersion" -ge "160" && "$parsedsamtoolsVersion" -lt "999" ]]; then
        echo "*** Valid samtools version is detected - installed version: "$samtoolsversion
else
    echo "ERROR ====>>> Invalid samtools version : "$samtoolsversion
    echo " - should be at least 1.6 !!! FitHiChIP quits !!!"
    errcond=1
    # exit 1
fi
```

parsedsamtoolsVersion is 110, in my case, and not between 16 and 99. It may be better to check for the major version first (i.e "1") and then check for the minor version next (i.e. "10")

**Comment by ay-lab** [comment]
Hi @jaavedm 
Thanks for your feedback. I'll look into it. For the moment, please replace the line 453 with the code "if [ 1 == 0 ]; then" and execute. That'll disable the version checking. I'll check it in detail.

**Comment by ay-lab** [comment]
Hi @jaavedm 
I have modified the code "FitHiChIP_HiCPro.sh" regarding the testing of installed packages and their versions. Please check and inform for any queries. Thanks for your feedback.

**Comment by jaavedm** [comment]
Thank you
