### ISSUE TITLE
Input files for PeakInferHiChIP.sh

### ISSUE THREAD

**Issue by pjlaw** [ay-lab/FitHiChIP#36]
When there are multiple *.validPairs, *.DEPairs, *.REPairs, and *.SCPairs files in the input directory, the PeakInferHiChIP.sh script will only load one of each file. I'm not sure if this is the intended behaviour.

When iterating over the files, eg lines 95-98
```
for f in `find $HiCProBasedir -type f -name *.DEPairs`; do
	DEReadFile=$f
	cnt=`expr $cnt + 1`
done
```
`DEReadFile` will be set to the last file that is iterated over. I should be something like `DEReadFile="${DEReadFile} ${f}"`

And similar for lines 107, 118, and 129.

**Comment by ay-lab** [comment]
Hi @pjlaw 
Thanks for your query. HiCPro generates one file per sample for each of these pair types. I am not sure why your input folder contains multiple files for them. Are you trying to infer peaks from merged HiChIP data? In such a case, please merge the fastq samples first, run HiC-pro on the merged fastq files, and then call peaks.

**Comment by pjlaw** [comment]
Thanks for the response. I'm using the nextflow HiCPro, which generates a set of output files for each fastq read pair. I'll merge them before calling peaks.
