### ISSUE TITLE
PeakInferHiChIP MACS2 problem

### ISSUE THREAD

**Issue by harbourlab** [ay-lab/FitHiChIP#38]
Hi!

While running PeakInferHiChIP I encounter the following error: 

ImportError: /nethome/sxk321/.local/lib/python2.7/site-packages/MACS2/IO/Parser.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8

Any idea what that could be? Full command below:

PeakInferHiChIP.sh -H /projects2/med/hlab/stefan/Big_ChIP_run/Stefan_Hi_ChIP/HiC_output/hic_results/data/2020-01-17-Stefan-UMC026_EV_CTCF-Hi-ChIP_L001_ds.947617d3f78e4d54bd7af143fedd9289 -D /nethome/sxk321/CTA/UM/Hi-ChIP-peaks -R hs -L 100
ReadLength : 100
halfreadlen: 50
File containing DE reads: /projects2/med/hlab/stefan/Big_ChIP_run/Stefan_Hi_ChIP/HiC_output/hic_results/data/2020-01-17-Stefan-UMC026_EV_CTCF-Hi-ChIP_L001_ds.947617d3f78e4d54bd7af143fedd9289/2020-01-17-Stefan-UMC026-EV-CTCF-Hi-ChIP_S10_L001_001_GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.bwt2pairs.DEPairs
File containing SC reads: /projects2/med/hlab/stefan/Big_ChIP_run/Stefan_Hi_ChIP/HiC_output/hic_results/data/2020-01-17-Stefan-UMC026_EV_CTCF-Hi-ChIP_L001_ds.947617d3f78e4d54bd7af143fedd9289/2020-01-17-Stefan-UMC026-EV-CTCF-Hi-ChIP_S10_L001_001_GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.bwt2pairs.SCPairs
File containing RE reads: /projects2/med/hlab/stefan/Big_ChIP_run/Stefan_Hi_ChIP/HiC_output/hic_results/data/2020-01-17-Stefan-UMC026_EV_CTCF-Hi-ChIP_L001_ds.947617d3f78e4d54bd7af143fedd9289/2020-01-17-Stefan-UMC026-EV-CTCF-Hi-ChIP_S10_L001_001_GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.bwt2pairs.REPairs
File containing valid pairs: /projects2/med/hlab/stefan/Big_ChIP_run/Stefan_Hi_ChIP/HiC_output/hic_results/data/2020-01-17-Stefan-UMC026_EV_CTCF-Hi-ChIP_L001_ds.947617d3f78e4d54bd7af143fedd9289/2020-01-17-Stefan-UMC026-EV-CTCF-Hi-ChIP_S10_L001_001_GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.bwt2pairs.validPairs
Traceback (most recent call last):
  File "/nethome/sxk321/miniconda3/envs/Stefan_HiChIP_final/bin/macs2", line 650, in <module>
    main()
  File "/nethome/sxk321/miniconda3/envs/Stefan_HiChIP_final/bin/macs2", line 48, in main
    from MACS2.callpeak_cmd import run
  File "/nethome/sxk321/.local/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/nethome/sxk321/.local/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
ImportError: /nethome/sxk321/.local/lib/python2.7/site-packages/MACS2/IO/Parser.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8

**Comment by ay-lab** [comment]
Hi, this seems like a MACS problem and it seems to be discussed on their
forum: https://github.com/taoliu/MACS/issues/196
Best,
