### ISSUE TITLE
ERROR Samtools version should be at least 1.6

### ISSUE THREAD

**Issue by JiaoLaboratory** [ay-lab/FitHiChIP#39]
My Samtools is version: 1.9，it still is ERROR !
*** Found MACS2 package (for peak calling) installed in the system -  (most
Installed R version: 3.3.3
Installed samtools version: 1.9
*** bgzip utility is installed in the system
*** tabix utility is installed in the system
 - Samtools version should be at least 1.6 !!! FitHiChIP quits !!!
 --------->>>>>> ERROR - current system has one or more packages missing
 ------- please check the above logs and install the missing packages before executing FitHiChIP
 ------- exiting for the moment !!

**Comment by ay-lab** [comment]
Hi @kunproj 
Thanks for your query. Please confirm if you have used the latest FitHiChIP code (by cloning the repository). I have checked these issues before. If the latest code is also having this issue, I'll fix it and let you know ASAP.

**Comment by JiaoLaboratory** [comment]
hi, ay-lab 
Yes，I re-cloned  the repository，I get the same issue !
$git clone https://github.com/ay-lab/FitHiChIP.git
$cd FitHiChIP
$bash sample_script.sh
 ================ Parsing input configuration file =================
Content of ValidPairs is ./TestData/Sample_ValidPairs.txt.gz
Content of Interval is
Content of Matrix is
Content of Bed is
Content of PeakFile is ./TestData/Sample.Peaks.gz
Content of OutDir is ./TestData/results/
Content of IntType is 3
Content of BINSIZE is 5000
Content of LowDistThr is 20000
Content of UppDistThr is 2000000
Content of UseP2PBackgrnd is 0
Content of BiasType is 1
Content of MergeInt is 1
Content of QVALUE is 0.01
Content of ChrSizeFile is ./TestData/chrom_hg19.sizes
Content of PREFIX is FitHiChIP
Content of OverWrite is 1

 ================ Verifying input configuration parameters =================
***** Specified output directory : ./TestData/results/
HiC-pro is installed in the system
Installed HiC-pro version: 2.11.4
Installed python version: 2.7.15
*** Python library gzip is installed
*** Python module OptionParser (from the package optparse) is installed
*** Python package networkx is installed
*** Found MACS2 package (for peak calling) installed in the system -  (most
Installed R version: 3.3.3
Installed samtools version: 1.9
*** bgzip utility is installed in the system
*** tabix utility is installed in the system
 - Samtools version should be at least 1.6 !!! FitHiChIP quits !!!
 --------->>>>>> ERROR - current system has one or more packages missing
 ------- please check the above logs and install the missing packages before executing FitHiChIP
 ------- exiting for the moment !!

 @ay-lab

**Comment by ay-lab** [comment]
Hi @kunproj 
Thanks for your response. I have updated the code. Actually the error message itself was incorrect. The error was actually due to the bedtools version, which should be at least 2.26.0. I have fixed the code. Please reply if anything goes wrong.
