### ISSUE TITLE
Error in DGEList(counts = CountData, group = GroupDistrVec) when running DiffAnalysisHiChIP.r

### ISSUE THREAD

**Issue by dmcbffeng** [ay-lab/FitHiChIP#40]
Hi,

I was running Imp_Scripts/DiffAnalysisHiChIP.r for differential analysis. This is my input:

> Rscript ../FitHiChIP/Imp_Scripts/DiffAnalysisHiChIP.r \
>   --AllLoopList control/FitHiChIP_Peak2Peak_b25000_L20000_U3000000/Coverage_Bias/FitHiC_BiasCorr/FitHiChIP.interactions_FitHiC.bed,4943/FitHiChIP_Peak2Peak_b25000_L20000_U3000000/Coverage_Bias/FitHiC_BiasCorr/FitHiChIP.interactions_FitHiC.bed \
>   --ChrSizeFile hg38.chrom.sizes --FDRThr 0.1 \
>   --ChIPAlignFileList raw/control_H3K27ac_hg38.bam,raw/4943_h3k27ac_unique_picard.bam \
>   --OutDir control_vs_4943 --CategoryList control,4943 --DiffFDRThr 0.1

And I got this error:

>  **** Bin size of FitHiChIP loops : 25000 
> 
>  ===>> Merging ChIP coverage - processing ChIP-seq alignment file in BAM format : raw/control_H3K27ac_hg38.bam ====>> 
> 
>  ===>> Merging ChIP coverage - processing ChIP-seq alignment file in BAM format 👍 raw/4943_h3k27ac_unique_picard.bam ====>> 
> 
>  ===>> Scaling ChIP coverage - scaling_factor : NA ====>> 
> 
> 
>  *** Performed scaling of ChIP coverage values for uniform ChIP coverage *** 
> 
> 
>  ===>>> GroupDistrVec : HSPC	  
>  ===>>> GroupDistrVec : 4943	 Error in DGEList(counts = CountData, group = GroupDistrVec) : 
>   The count matrix is a data.frame instead of a matrix and 1 columns are non-numeric.
>   Should these columns be gene annotation instead of counts?
> Calls: ApplyEdgeR -> DGEList
> Execution halted

Is that because of something wrong in my bam files? Thank you so much!

**Comment by dmcbffeng** [comment]
I tried to replace 4943 with another cell line. And now it works.
Does the alignment file need to meet some requirements?

**Comment by ay-lab** [comment]
Hi @dmcbffeng 
Thanks for your query. The output "Scaling ChIP coverage - scaling_factor : NA" means that there was some error in processing the alignment file and computing the coverage. You may test with custom "bedtools coverage" routine on that alignment file to see if there is any issue in the alignment file.
