### ISSUE TITLE
Possible to use FitHiChIP without X11?

### ISSUE THREAD

**Issue by clagiamba** [ay-lab/FitHiChIP#41]
Hi,

X11 is not available in the clusters I am using (X11 is not active on the nodes and everything is compiled excluding x11). 
So, the pipeline stops and does not call loops:

```
temp_sum : 33305202020000 nelem_all_possble : 12544466 avg_int_dist[bin_idx] : 2654971 Error in grDevices::png(..., res = dpi, units = "in") :
  X11 is not available
Calls: ggsave -> dev -> <Anonymous>
Execution halted
******** FINISHED calling significant interactions
ERROR !!!!!!!! FitHiChIP could not compute the statistical significance of input interactions

```

Is it possible to get FitHiChIP to call loops independently and excluding the use of X11?
Thank you,
Claudia

**Comment by ay-lab** [comment]
Hi @clagiamba 
Thanks for your query. Can you please check the following?
1) Whether you are using the latest code. All the plots in the latest code uses ggplot2 package.
2) If ggplot2() package is installed in your cluster, and whether it works for any sample plot. Like 
Please confirm if your cluster does not support any such plotting. Then I'll put an option in the code to run it without any plots.

**Comment by clagiamba** [comment]
Hi! Thank you Sourya!

The ggplot2 was loading but the cluster does not support X11 so the "png" plot was giving an error:
> library(ggplot2)
> ggplot(mtcars, aes(mpg, wt)) + geom_point()
> ggsave("mtcars.png”)

but the problem was solved by adding  in the file ~/.Rprofile this to use backend Cairo:
options(bitmapType='cairo')

Many thanks!
