### ISSUE TITLE
can we analyse capture HiC data using FitHiChIP ? can you provide some specification for the same? 

### ISSUE THREAD

**Issue by bioarpit1** [ay-lab/FitHiChIP#42]
Hi Sourav/Ferhat, 

Recently from ISMB talk i vaguely remeber Ferhat said FitHiChIP pipeline can be used for analysing capture HiC data as well. Would you provide some further information about what changes do i need to do in configuration file where do I provide my capture probe information. Currently i am using chicago, for the analysis and just want to compare its output with FitHiChIP. 

Thanks

Arpit

**Comment by ay-lab** [comment]
Hi @bioarpit1 
Thanks for your query. I have added the brief procedure here: https://ay-lab.github.io/FitHiChIP/usage/Utilities.html (8th point). Please check and notify me for any questions.
