### ISSUE TITLE
Is this pipeline compatible with MNase-based protocols ?

### ISSUE THREAD

**Issue by danledinh** [ay-lab/FitHiChIP#44]
ref: https://dovetailgenomics.com/hichip-product-page/

Is this pipeline compatible with MNase-based protocols ?

**Comment by ay-lab** [comment]
Hi, I do not see any reason why FitHiC2 or FitHiChIP would not be applicable to this kind of data. Whether they would be the ideal/best tool, we have to test and see. 
Some things to consider if you want to apply FitHiChIP to MNase HiChIP:
- Are you interested in all loops between any pair of loci? If so then run it in all to all mode and do not worry about peak calling?
- Would you prefer to focus on loops that involve an MNase peak on at least one side (or both)? Then you will have to do the peak calling in the best way possible for the MNase data yourself (if you believe MACS with our ChIP-seq-minded settings are not the best) and then input those into FitHiChIP.

I hope this helps.

**Comment by danledinh** [comment]
Thanks for the suggestions.
