### ISSUE TITLE
Is it possible to use FitHiChIP without X11?

### ISSUE THREAD

**Issue by margaretwoodhouse** [ay-lab/FitHiChIP#45]
Hi, there:

I'm running FitHiChip on an HPC cluster that doesn't support X11, and I keep getting this error:

```
 X11 is not available
Calls: ggsave -> dev -> <Anonymous>
Execution halted
******** FINISHED calling significant interactions
ERROR !!!!!!!! FitHiChIP could not compute the statistical significance of input interactions
```

Is there a way to run this without X11? ggplot2 is installed, but the HPC compute cluster does not support X11, so I'm not able to complete FitHiChip on my system.

**Comment by ay-lab** [comment]
Hi @margaretwoodhouse 
Are you still having this issue?

**Comment by lldelisle** [comment]
Hi,
I got the same issue. To solve it I did:
`sed -i 's/png/pdf/g' FitHiChIP/src/FitHiC_SigInt.r`

**Comment by jaavedm** [comment]
I put the following lines at the beginning of each .R file that has a call to ggsave

`options(bitmapType='cairo')`

I find that I still want to make the PNG files so that they are included in the final HTML results.
