### ISSUE TITLE
Use of bam or bdg or bed from MErgeBAMinferPeaks for differential analysis module ?

### ISSUE THREAD

**Issue by Politropos** [ay-lab/FitHiChIP#46]
I am confused on which peak files I should be using for the differential analysis module.
Following the instructions of the diff module I have been using either Bam files from independent chipseq sets performed on the same cells as the HICHIP or the gz bedgraph files generated by the PeakInferHICHIP utility. Your DiffanalysisHICHIP.r code and its execution indicates that merging and asignemnet of coverage according to bin size is done by this utility
However I noticed that the MergeBAmInferPeaks that outputs bed files of the right bin size as used for FITHICHIP  indicates that outputs from this utility should be used for the diff analysis module. However these are bed files 
Can you please advise which ones  to use
Thank you

**Comment by ay-lab** [comment]
Hi @Politropos 
In differential analysis module, you need to provide ChIP-seq alignment files in either bam or bedgraph format. The ChIP-seq coverage w.r.t the specified bin size is computed within the differential analysis script, so no need to use the MergeBAMInferPeaks script. That script was provided for calling ChIP-seq peaks which are provided as an input to FitHiChIP loop calling.
