### ISSUE TITLE
The output file “ *PREFIX*.interactions_FitHiC_Q”qval”_MergeNearContacts.bed” is not clear

### ISSUE THREAD

**Issue by wbszhu** [ay-lab/FitHiChIP#50]
Hi，
The relationship between CC and SumCC and StrongConn is not very clear , especially SumCC. Can you explain it? If I need to choose a value as the strength of loop, which one should I choose as the representative?

Thank you.

**Comment by ay-lab** [comment]
Hi @wbszhu 
Thanks for your query. Please check the updated documentation in 
https://ay-lab.github.io/FitHiChIP/usage/output.html#details-of-output-files
(sections _Details of FitHiChIP significant interactions_ and _Details of merge filtering output_ )

The merge filtering operation already puts the best loop within a connected component, and discards the surrounding loops. If you want to rank these loops, you can use contact count (field 7) or q-value (field 9).

**Comment by wbszhu** [comment]
Thank you.

Hi @wbszhu
Thanks for your query. Please check the updated documentation in
https://ay-lab.github.io/FitHiChIP/usage/output.html#details-of-output-files
(sections Details of FitHiChIP significant interactions and Details of merge filtering output )

The merge filtering operation already puts the best loop within a connected component, and discards the surrounding loops. If you want to rank these loops, you can use contact count (field 7) or q-value (field 9).

**Comment by wbszhu** [comment]
Hi,
There is another question.We want to compare and rank loops, so for each loop, we use the −log10qvalue for interactions strength. However, for some loops, their q-values equal to zero. We assumed this is limited by the precision of float? Can you provide an accurate q-value even if it is very small instead of using zero?
Thank you.
