### ISSUE TITLE
how to combine HiChIP loops

### ISSUE THREAD

**Issue by BenxiaHu** [ay-lab/FitHiChIP#51]
Hi,
   I used FitHiChIP processed HiChIP. Now I want to combined loops called from replicated samples.
   Do you have any idea to merge loops together?
Best

**Comment by ay-lab** [comment]
Hi @biohubx 
If I understand your question correctly, you have two HiChIP replicates R1 and R2, and you have already generated the FitHiChIP significant loops for both R1 and R2. Now you want to combine these two sets of significant loops.
One option is to simply take the union of these loops. But a better option would be to merge the validpairs from R1 and R2 to get a combined validpairs file R, and call FitHiChIP significant loops from this merged sample.
Please let me know for any further queries.

**Comment by BenxiaHu** [comment]
Thanks a lot
