### ISSUE TITLE
Intra- and Inter-chromosomal loops

### ISSUE THREAD

**Issue by shanwai1234** [ay-lab/FitHiChIP#52]
Hello,

I run Fithichip and got significant loops as results. However, I only see intrachromosomal loops but there is no interchromosomal loops detected. I found I have interchromosomal valid pairs from the valid pair file. I just wonder if Fithichip can only apply for calling intrachromosomal loops? Thank you!

**Comment by ay-lab** [comment]
Hi @shanwai1234 
Thanks for your query. Yes FitHiChIP detects only the significant intra-chromosomal loops for the specified distance thresholds mentioned in the configuration file.
If you want the inter-chromosomal loops, I would suggest to check our **FitHiC2** package. Although the package is for Hi-C data, it would process HiChIP data as well.

**Comment by shanwai1234** [comment]
Thank you!
