### ISSUE TITLE
How to generate Bed containing the locus pairs (binned) and the contact count

### ISSUE THREAD

**Issue by robeach78** [ay-lab/FitHiChIP#53]
Hi all ,
I have got to the point of running HiC-pro.

Now I wanna use FitHiChIP, but the only thing I am missing is the:

A.4) Bed:

        Tab delimited text file containing the locus pairs (binned) and the contact count.
        **Of the format: chr1 start1 end1 chr2 start2 end2 contact**
        Can be generated from any HiC or HiChIP data processing pipelines, or custom scripts.

how do I get this bed files    **Of the format: chr1 start1 end1 chr2 start2 end2 contact** (with this format)
from the HiC-pro outputs?

Thanks a lot,
Roberto

**Comment by ay-lab** [comment]
Hi @robeach78 
Thanks for your query. Not all of the parameters A.1 to A.4 are needed. They are three different input options for this pipeline. Please check the documentation https://ay-lab.github.io/FitHiChIP/usage/configuration.html.
You can specify any of the three input options:
A.1) Valid pairs file (*.allValidpairs) from HiCPro pipeline
A.2 and A.3) interval file *_abs.bed and matrix file *.matrix from HiCPro pipeline
A.4) Bed file containing contacts, when the HiChIP data or the input contacts were generated by any other packages except HiCPro.
Once you set a particular input option,  you can keep the other configuration parameters blank. For example, using the parameter (A.1), your configuration file will be:
Validpairs=_your_input_validpairs_path_
Interval=
Matrix=
Bed=
Please let me know for any question.
