### ISSUE TITLE
mcfork error while using TestData

### ISSUE THREAD

**Issue by sillysean** [ay-lab/FitHiChIP#59]
Hi there,

Something goes wrong with the mcfork When I run the FitHiChIP tool with TestData， 
```
Error in mcfork() :
  unable to fork, possible reason: Cannot allocate memory
Calls: AllPossibleContacts ... as.data.frame -> <Anonymous> -> lapply -> FUN -> mcfork
Execution halted
```
But my server shows that there is still plenty of memory.

My command is
`bash FitHiChIP_HiCPro.sh -C configfile_BiasCorrection_CoverageBias`
While the parameters in my configuration file mostly remain default.

There are the log and configuration files in the attachment.

Thanks :-)

[coverage_bias.log](https://github.com/ay-lab/FitHiChIP/files/6141882/coverage_bias.log)
[configfile_BiasCorrection_ICEBias.txt](https://github.com/ay-lab/FitHiChIP/files/6141887/configfile_BiasCorrection_ICEBias.txt)

**Comment by ay-lab** [comment]
Hi @sillysean 
Can you please git clone the latest code and try it once more? Please let me know.

**Comment by sillysean** [comment]
> Hi @sillysean
> Can you please git clone the latest code and try it once more? Please let me know.

Thanks for your reply.

I've got the latest code but it cannot detect HiC-Pro though I've added HiC-Pro into the PATH. 
And it reported that,

`ERROR ====>>> As user did not provide any pre-computed locus pairs (along with their contact count) in BED input, neither provided the HiC-pro base installation directory, FitHiChIP quits - exit !!`

I did not change the configuration parameters and still using the TestData.

When I switch to the former version of FitHiChIP, it goes well in the stage of _Verifying input configuration parameters_.

**Comment by souryacs** [comment]
Hi @sillysean 
Does the issue still persist? Please let me know.

**Comment by SoManyPepople** [comment]
I have just met the same issue and resolved it by manually modifying the two R scripts ('src/FitHiC_SigInt.r' and 'src/Interaction.r').
Specifically, just find the line "ncore <- detectCores()" and modify it as "ncore <- floor(detectCores() * 0.8)".
