### ISSUE TITLE
promoter capture Hi-C analysis

### ISSUE THREAD

**Issue by BenxiaHu** [ay-lab/FitHiChIP#61]
hello,
    based on this tutorial (https://ay-lab.github.io/FitHiChIP/usage/Utilities.html#applying-fithichip-on-capture-hic-data), do I need to provide **the design bait file of the promoter capture HiC data** when running the step 2?
I want to analyze these pcHiC (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE113481) using FitHiChIP.
Best,

**Comment by souryacs** [comment]
Hi @BioEpi 
Sorry for the late reply. You need to provide the bait intervals, which will act as the input peak regions for FitHiChIP. Please let me know if it helps.
