### ISSUE TITLE
Is there a way to visualize the arcs plot in IGV?

### ISSUE THREAD

**Issue by jiangshan529** [ay-lab/FitHiChIP#62]

**Comment by jiangshan529** [comment]
I just feel it is too slow to load a gene in WashU genome browser.

**Comment by souryacs** [comment]
Hi @jiangshan529 
You can manually convert the FitHiChIP significant interactions (*FitHiC_Q0.01.bed, considering FDR = 0.01) into bedpe format, and load that file into IGV. Please let me know if it works.

**Comment by mctackett20** [comment]
how does one manually convert the FitHiChIP bed file into a bedpe file for this purpose?

**Comment by ay-lab** [comment]
Hi @mctackett20 
We have just made a new release of FitHiChIP which produces the IGV compatible bedpe files from FitHiChIP loops. In addition, it also generates WashU and UCSC compatible files from the significant interactions. Please check the latest code.

The awk command for this conversion:
awk -F['\t'] 'function min(x,y) {return x < y ? x : y} {if (NR > 1) {if ($NF > 0) {x=min(500,-log($NF)/log(10))} else {x=500}; print $1"\t"(($2+$3)/2-1)"\t"(($2+$3)/2+1)"\t"$4"\t"(($5+$6)/2-1)"\t"(($5+$6)/2+1)"\t-\t"x"\t.\t."}}' **${FitHiC_SigFile}** | sort -k1,1 -k2,2n -k5,5n > **${IGVFile}**

**Comment by koushik20** [comment]
Hi @ay-lab 
I have generated significant interactions bed files with the previous version of FitHiChIP. Can you please share the command you used to convert the bed files into UCSC compatible files?

Thank you!

**Comment by ay-lab** [comment]
Hi @koushik20 

To convert the FitHiChIP interactions to UCSC compatible format, please run the following commands:

ColorStr="#0000FF"		

awk -F'[\t]' -v c="$ColorStr" '{if (NR>1) {if ($NF>0) {a=int(-log($NF)/log(10)) + 1} else {a=500}; print $1"\t"(($2+$3)/2-1)"\t"(($5+$6)/2+1)"\t.\t"a"\t"$7"\t.\t"c"\t"$1"\t"(($2+$3)/2-1)"\t"(($2+$3)/2+1)"\t.\t.\t"$4"\t"(($5+$6)/2-1)"\t"(($5+$6)/2+1)"\t.\t."}}' $FitHiChIPFile | sort -k1,1 -k2,2n -k3,3n > $tempfile1
		
${bedToBigBedExec} -as=${interact_as_file} -type=bed5+13 ${tempfile1} $ChrSizeFile ${OutFile}
		
rm ${tempfile1}

Where, 
$FitHiChIPFile: file containing FitHiChIP significant interactions (*FitHiC_Q0.01.bed)
$tempfile1: a temporary file (like temp.txt)
$bedToBigBedExec: bed to bigbed executable downloaded from UCSC
${interact_as_file}: Interact data format - downloaded from UCSC
$ChrSizeFile: reference genome specific chromosome size file (like hg19_chr.sizes) - downloaded from UCSC
$OutFile: Output UCSC compatible bed file like "Out_UCSC.bed"

**Comment by SplitInf** [comment]
Hello @ay-lab

Can you please explain what's the rationale behind the above awk code? For example, the IGV conversion awk one-liner converts the bin region into the middle point. But what is the meaning of x?

Also, is this behaviour same as [DiffLoop_IGV_Convert()](https://github.com/ay-lab/FitHiChIP/blob/0ea1ac21be870908c672316ffbb630189dc6fae2/Imp_Scripts/DiffAnalysisHiChIP.r#L59-L64) since it is fix at the value 10.
