### ISSUE TITLE
curious about peak to all and peak to peak

### ISSUE THREAD

**Issue by jiangshan529** [ay-lab/FitHiChIP#63]
Hi, I have a HiChIP dataset, If I use all to all model, there are about 40,000 contacts, but whether I use peak to all or peak to peak, there are 1000 contacts, I think anyway there should be more contacts if using peak to all model, is there any explanation?

**Comment by souryacs** [comment]
Hi @jiangshan529 
Peak-to-all mode considers interactions whose at least one end overlaps with the given set of peaks. The peak-to-peak model considers only those interactions whose both ends overlap with the given set of peaks. It is expected that the peak-to-all model would have a higher number of contacts, but that depends on the input data. In your input data, there may not be any peak-to-nonpeak contacts (i.e. one end overlaps with a peak while the other end does not). Can you please check that, using standard bedtools routine, and let me know?

**Comment by jiangshan529** [comment]
> Hi @jiangshan529
> Peak-to-all mode considers interactions whose at least one end overlaps with the given set of peaks. The peak-to-peak model considers only those interactions whose both ends overlap with the given set of peaks. It is expected that the peak-to-all model would have a higher number of contacts, but that depends on the input data. In your input data, there may not be any peak-to-nonpeak contacts (i.e. one end overlaps with a peak while the other end does not). Can you please check that, using standard bedtools routine, and let me know?

Hi, I am sure that my data has good quality of hichip(I can call about 20,000 peaks) but has little reads(20M). I can detect about 20,000  significant contacts in alltoall mode, and I find 4844 contacts only have peak on the left side. So it means my data has peak-to-nonpeak contacts. Are there any possible reasons? It seems that coverage bias is for MNase but not restriction enzyme, I used coverage bias for restriction enzyme, is that the reason?

**Comment by ay-lab** [comment]
Not sure what you mean by MNase bias, isn't your HiChIP generated using RE? Anyway, I do not think that is the reason. 
The behavior you are summarizing is the expected behavior. All2all gives you a much lower expected signal that then translates into a higher number of contacts. If you are happy with those results you can just go with that and explain. 20M is not a lot of reads to get 10s of thousands of loops for the stringent background so I am not surprised.

**Comment by jiangshan529** [comment]
> Not sure what you mean by MNase bias, isn't your HiChIP generated using RE? Anyway, I do not think that is the reason.
> The behavior you are summarizing is the expected behavior. All2all gives you a much lower expected signal that then translates into a higher number of contacts. If you are happy with those results you can just go with that and explain. 20M is not a lot of reads to get 10s of thousands of loops for the stringent background so I am not surprised.

Hi, Now I am reproducing data from a paper, which has about 200M raw reads. for the call peak step, I use both macs2 and hichip-peaks(https://github.com/ChenfuShi/HiChIP_peaks), hichip-peaks identified 7943 peaks, while macs2 identified 870355 peaks, and I use peaktoall mode to find significant interactions, as shown in the figure attached, using hichip peaks can only detect 3000-4000 arcs from 200M raw reads(which I think is too little), using macs2 peaks can detect 14000+ arcs(which I think should be normal). 
So my question here is: 
1. Using hichip-peak identified peaks(which highly fits the bw tracks) detect fewer interactions, but I think macs2 identified peaks are not authentic, or do you think Macs2 peaks are also ok?(according to the bw track)
2. And I find more than 90 percent of the arcs have two ends overlapped with the peak even though using peaktoall mode, is that correct?(because I think there should be more arcs between peak to non-peak regions)
![image](https://user-images.githubusercontent.com/75197626/120093865-93222e00-c14f-11eb-8122-90d30ad5aece.png)
