### ISSUE TITLE
is there any normalization step?

### ISSUE THREAD

**Issue by jiangshan529** [ay-lab/FitHiChIP#64]
Hi, I want to know if there's any normalization step in the differential analysis? What if two samples are hugely different in reads counts?
Thanks

**Comment by souryacs** [comment]
Hi @jiangshan529 
The differential ChIP (1D) bin analysis already takes into account the difference in sequencing depths, before attributing individual bins as differential or non-differential. On the other hand, differential HiChIP contacts are obtained by EdgeR, which also considers differences in sequencing depths to estimate the size factors.

**Comment by jiangshan529** [comment]
> Hi @jiangshan529
> The differential ChIP (1D) bin analysis already takes into account the difference in sequencing depths, before attributing individual bins as differential or non-differential. On the other hand, differential HiChIP contacts are obtained by EdgeR, which also considers differences in sequencing depths to estimate the size factors.

Thanks for your reply. I have another question. When I use peaktoall mode, sometimes there are even less contacts than peaktopeak mode. I think there must be something wrong with it.
