### ISSUE TITLE
how to do differential analysis for drug treated sample?

### ISSUE THREAD

**Issue by jiangshan529** [ay-lab/FitHiChIP#65]
Hi, I am doing hichip analysis for TF1, and I add some drugs to see how the looping of TF1 will be influenced. Now I want to perform differential analysis to see which contacts changed after drug treatment. I only have chip-seq bam files for wild type TF1, and I don't have chip-seq bam files for drug treated TF1, so how should I set the parameter "ChIPAlignFileList"?

**Comment by souryacs** [comment]
Hi @jiangshan529 
Sorry for such late response. Currently FitHiChIP needs representative ChIP-seq files from both categories. We are planning to implement one differential analysis version without any ChIP-seq input. We'll let you know. Meanwhile you can send us any suggestions or issues regarding the differential analysis. Thanks.
