### ISSUE TITLE
Differential Loop Analysis

### ISSUE THREAD

**Issue by vivianschu** [ay-lab/FitHiChIP#66]
Hi,

I've encountered a problem trying to get FitHiChIP's Differential Loop Analysis script to run:
```
 **** Bin size of FitHiChIP loops : 2500

 ===>> Merging ChIP coverage - processing ChIP-seq alignment file in BAM format : /home/vchu/scratch/sgSOX2/Diff_K140_broad/K140A1_Align.hg19.bam ====>>
sh: line 1: 249548 Killed                  bedtools coverage -a /home/vchu/scratch/sgSOX2/Diff_K140_broad/out/Binned_Chromosome_Size_RefGenome.bed -b /home/vchu/scratch/sgSOX2/Diff_K140_broad/K140A1_Align.hg19.bam -counts > /home/vchu/scratch/sgSOX2/Diff_K140_broad/out/ChIP_Coverage_ALL.bed

 ===>> Merging ChIP coverage - processing ChIP-seq alignment file in BAM format : /home/vchu/scratch/sgSOX2/Diff_K140_broad/K140S3_Align.hg19.bam ====>>
Warning message:
In data.table::fread(MergedChIPCovFile, header = F, sep = "\t",  :
  File '/home/vchu/scratch/sgSOX2/Diff_K140_broad/out/ChIP_Coverage_ALL.bed' has size 0. Returning a NULL data.frame.
Error in `[.data.frame`(Merged_ChIPCovData, , 4) :
  undefined columns selected
Calls: [ -> [.data.frame
Execution halted
```

I've sorted and indexed my input bam files, so I'm unsure of what the error is here. Would you be able to help?

**Comment by souryacs** [comment]
Hi @vivianschu 
Thanks for your query. As you can see, "sh: line 1: 249548 Killed" means there is a memory allocation issue while converting the input alignment file. Please provide more memory in your job submission script, and it should work.

**Comment by vivianschu** [comment]
Do you have a recommendation on how much memory I should allocate? I tried 100GB with 12 CPUs... seems like too much for the data that I have. It still halts at the bedtools coverage step.

**Comment by souryacs** [comment]
Hi @vivianschu 
Please try 200 GB memory. Your ChIP-seq data may have high sequencing depth. I've encountered such issues before, and 200 GB is the maximum memory I needed to allocate.

**Comment by vivianschu** [comment]
Thank you!
