### ISSUE TITLE
More details about the example data

### ISSUE THREAD

**Issue by zxwang2019** [ay-lab/FitHiChIP#67]
Thank you very much for providing such a great pipeline. Here, I want to know the sample data used for testing, including the "sample.peaks.gz" from ChIP-seq analysis and the "analysis_ Validpairs.txt.gz" from Hi-C analysis, where are they obtained? Are they from a published paper? If so, I would appreciate it if you could provide me with the PMID.

**Comment by souryacs** [comment]
Hi @zxwang2019 
Thanks for your query. You can check the GEO GSE101498, GSE80820 for sample HiChIP validpairs files for Human and Mouse, and for various histone modifications. For example, within GSE101498, the IDs GSM2705041 and GSM2705042 contain two replicates of Human GM12878 H3K27ac HiChIP data (hg19 reference genome).

For the ChIP-seq peaks, you need to search the compatible cell line / type and histone modifications in ENCODE. For example, Human GM12878 H3K27ac ChIP-seq data for hg19 is provided in https://www.encodeproject.org/experiments/ENCSR000AKC/. Choose hg19 as the reference genome, click "File Details" and get the file "ENCFF361XMX" (replicated peaks, bed narrowpeak format).

Hope this helps. Please let me know for any further information.

**Comment by zxwang2019** [comment]
Thanks a lot for your reply!
