### ISSUE TITLE
CHIP-seq inferred from HICHIP peak

### ISSUE THREAD

**Issue by xumai-du** [ay-lab/FitHiChIP#69]
If we use PeakInferHiChIP.sh to infer the ChIP-seq peak from HIChIP data, we got *.narrowPeak formatted peak file. Is it OK for Histone HICHIP as *.broadPeak formatted peak files are normally used for many other applications? Thanks!

**Comment by ay-lab** [comment]
Hi @xumai-du 
We recommend using narrow peak formatted files, since broad peaks are often much wide, and span a much higher region from the summits. Therefore, using narrow peak files would better indicate the protein enriched regions.
