### ISSUE TITLE
Halts at Regression Model

### ISSUE THREAD

**Issue by vivianschu** [ay-lab/FitHiChIP#70]
Hi, when running FitHiChIP, all scripts halt at the same line at the Regression model but does not crash (simply runs until there is no time left):

```
 === Regression model (training data) - average distance: 165000 number of interactions: 45444  number of bias threshold satisfying interactions: 42380

 === Regression model (training data) - average distance: 170000 number of interactions: 44950  number of bias threshold satisfying interactions: 41784

 === Regression model (training data) - average distance: 175000 number of interactions: 44457  number of bias threshold satisfying interactions: 41375
~
```
I am using 10 CPUs and 50 gb of memory. This is being run on GRCh38.
Do you have any ideas to why this is happening? Thanks!

**Comment by vivianschu** [comment]
I've downloaded the latest version of FitHiChIP and it seems to be halting at the same step for regression (does not fail, just keeps running):

```
 ****** Start regression - Equal Occupancy binning ****
```

Would you be able to help? Thanks!

**Comment by ay-lab** [comment]
Hi @vivianschu 
Thanks for your query. Could you please e-mail me (sourya@lji.org) the following?
1) output log file
2) The file "Bin_Info.log" within the same output directory containing FitHiChIP significant interactions
I'll check the output and get back to you soon.

**Comment by ay-lab** [comment]
Hi @vivianschu 
Are you still having the issue?

**Comment by ay-lab** [comment]
Hi @vivianschu 
Could you please "git clone" the current code and test it on your data? I've updated the parallel processing routine. Let me know if it solves your problem.

**Comment by vivianschu** [comment]
Hi @ay-lab, thanks for your help - everything works great now.
