### ISSUE TITLE
Error in hist.default(histdata$dist, breaks = seq(min_dist, max_dist,  :

### ISSUE THREAD

**Issue by hanshanmengqi** [ay-lab/FitHiChIP#72]
Dear,

Thank you for providing pretty useful tool.

But I got error when I run FitHiChIP_HiCPro.sh with test data. The error message:

"
    237 Warning messages:
    238 1: Use of `histdata$dist` is discouraged. Use `dist` instead.
    239 2: Use of `histdata$dist` is discouraged. Use `dist` instead.
    240 3: Use of `histdata$dist` is discouraged. Use `dist` instead.
    241 4: Removed 2 rows containing missing values (geom_bar).
......
    268 Warning message:
    269 In mean.default(DistVec) :
    270   l'argument n'est ni numérique, ni logique : renvoi de NA
    271 Warning message:
    272 In min(DistVec) : aucun argument trouvé pour min ; Inf est renvoyé
    273 Warning message:
    274 In max(DistVec) : aucun argument pour max ; -Inf est renvoyé
    275 Error in hist.default(histdata$dist, breaks = seq(min_dist, max_dist,  :
    276   'x' doit être numérique
    277 Calls: hist -> hist.default
    278 Exécution arrêtée
"

Could you tell me how can resolve this problem?
Thank you in advance.

**Comment by ay-lab** [comment]
Hi @hanshanmengqi 
Thanks for your query. Please check if you've got output significant interactions (*FitHiC_Q0.01.bed) at all. Check if any R libraries are not installed at your end. Otherwise, please post the output log so that I can take a look at it. Thanks.

**Comment by hanshanmengqi** [comment]
Dear,


Thank you very much for your reply and so prompt.


Actually, I have got&nbsp;&nbsp;all results I guess(include&nbsp;FitHiChIP_ALL2ALL_b2500_L10000_U2000000,&nbsp;FitHiChIP_Peak2ALL_b2500_L10000_U2000000&nbsp; HiCPro_Matrix_BinSize2500, NormFeatures 4 directories and related *FitHiC_Q0.01.bed files).


However, I'm worried that the results not complete because this error ("Error in hist.default(histdata$dist, breaks = seq(min_dist, max_dist,&nbsp; :").


The attachments are output file, error file and Summary_results_FitHiChIP.html .


I'm very much obliged to you.


Best wishes.
Hanshanmengqi




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ay-lab/FitHiChIP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月12日(星期六) 凌晨3:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ay-lab/FitHiChIP] Error in hist.default(histdata$dist, breaks = seq(min_dist, max_dist,  : (Issue #72)





 
Hi @hanshanmengqi
 Thanks for your query. Please check if you've got output significant interactions (*FitHiC_Q0.01.bed) at all. Check if any R libraries are not installed at your end. Otherwise, please post the output log so that I can take a look at it. Thanks.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hanshanmengqi** [comment]
Dear @ay-lab, 

Thank you very much for your reply and so prompt.

Actually, I have got all results I guess(include FitHiChIP_ALL2ALL_b2500_L10000_U2000000, FitHiChIP_Peak2ALL_b2500_L10000_U2000000, HiCPro_Matrix_BinSize2500, NormFeatures 4 directories and related *FitHiC_Q0.01.bed files).

However, I'm worried that the results not complete because this error ("Error in hist.default(histdata$dist, breaks = seq(min_dist, max_dist, :").

The attachments are output file and error file.

I'm very much obliged to you.

Best wishes.
Hanshanmengq
[execute_FitHiChIP_test_e.txt](https://github.com/ay-lab/FitHiChIP/files/8251466/execute_FitHiChIP_test_e.txt)
[execute_FitHiChIP_test_o.txt](https://github.com/ay-lab/FitHiChIP/files/8251468/execute_FitHiChIP_test_o.txt)

**Comment by ay-lab** [comment]
Hi @hanshanmengqi 
Thanks for your e-mail. I have updated the code (specifically Analysis/Distance_vs_CC.r). Please use the latest code and run once again. Please let me know for any queries. Thanks.
