### ISSUE TITLE
Indexing of large genomes

### ISSUE THREAD

**Issue by pna059** [ay-lab/FitHiChIP#74]
Hi,
I ran FitHiChIP on a genome with large chromosomes, beyond the index limit (coordinates larger than 2^29).
Got this error:
```
==================== End of merge filtering adjacent interactions !!! ======================
----- Applied merged filtering (connected component model) on the adjacent loops of FitHiChIP
[E::hts_idx_push] Region 536992499..536992501 cannot be stored in a tbi index. Try using a csi index with min_shift = 14, n_lvls >= 6
tbx_index_build failed: FitHiChIP_results/FitHiChIP_Peak2ALL_b5000_L10000_U3000000/P2PBckgr_0/Coverage_Bias/FitHiC_BiasCorr/Merge_Nearby_Interactions/FitHiChIP.interactions_FitHiC_Q0.01_MergeNearContacts_WashU.bed.gz
```
I suggest fixing this by adding -c option for these cases. Could you maybe navigate me to where to fix it in the current version?
Thank you!

**Comment by ay-lab** [comment]
Hi @pna059 
Thanks for your suggestion. Either you can use the generated "FitHiChIP.interactions_FitHiC_Q0.01_MergeNearContacts_WashU.bed.gz" file and index it manually, or edit the code "FitHiChIP_HiCPro.sh" (line: 1891). Thanks.
