### ISSUE TITLE
Very small number of significant interactions

### ISSUE THREAD

**Issue by arakawa7** [ay-lab/FitHiChIP#76]
HiChIP with MNase was performed on mouse cells, followed by analysis with HiCPRO and FitHiChIP.
Valid Read Pairs 80M PE reads
Config file settings for FithiChIP
IntType=3
BINSIZE=5000
LowDistThr=20000
UppDistThr=2000000
UseP2PBackgrnd=0
BiasType=1
MergeInt=1
QVALUE=0.01

FitHiChIP was performed using ChIP data from ENCODE.
Number of interacting (non zero contacts) bin pairs ( all to all ) 11191560
Number of interactions considered 561607
Total number of significant interactions 0
What are the reasons for significant interactions 0?

Also, if I use the inferred ChIP data from the HiChIP data
Number of interacting (non zero contacts) bin pairs ( all to all ) 10194721
Number of interactions considered 20004
Total number of significant interactions 45
Total number of significant interactions ( FDR 0.01 ) after merging adjacent loops 16
The number of interactions considered is very small.
What could be the problem?

**Comment by ay-lab** [comment]
Have you looked at QCs of your data and/or plotted heatmaps to see if you are able to visually identify specific loop patterns? Also the read depth is ok (not great) but maybe you would want to try 10kb or 20kb resolution to see if things change

**Comment by arakawa7** [comment]
Thanks for your reply.
I will try to do FitHiChIP again with the current data with a different
resolution.

Is there anything else to do with QCs in HiChIP besides checking the
quality of the library and the shape of the peaks, I am new to Hi-C and
HiChIP experiments and don't know how to do QCs.

2022年5月12日(木) 0:29 ay-lab ***@***.***>:

**Comment by ay-lab** [comment]
HiCPro already generates a lot of statistics and plots that can be used for QC. For Hi-C data, you can take a look at this paper from ENCODE, some ideas apply to HiChIP data as well: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1658-7

**Comment by arakawa7** [comment]
Thank you for your kind attention.
I will review the data generated by HiCPRO again and check the paper from
ENCODE as I was not aware of it.
I will use FitHiChIP again after QC confirmation.

2022年5月12日(木) 13:27 ay-lab ***@***.***>:
