### ISSUE TITLE
check the version

### ISSUE THREAD

**Issue by wbszhu** [ay-lab/FitHiChIP#77]
Hi,
Due to the change of server, we are now using results that are not sure what version number is used. How can I check the version of the FitHiChIP from the results?
Thanks a lot.

**Comment by ay-lab** [comment]
Hi @wbszhu 
Thanks for your query. Currently, FitHiChIP output does not explicitly mention the version. You can check the release logs and specific changes, and compare the source codes between GitHub and your downloaded version.

**Comment by wbszhu** [comment]
Hi,
Due to some reason. I did not keep the downloaded version. It seems to be no good solution.
