### ISSUE TITLE
WashU browser

### ISSUE THREAD

**Issue by jchap14** [ay-lab/FitHiChIP#8]
Hello,

I am trying to load the *.WashU.bed.gz & corresponding *.tbi to the WashU browser and not having any luck. Is there a tutorial or short description for how to do this somewhere?

Thanks,
James

**Comment by ay-lab** [comment]
Hi James,

Thanks for your feedback. Please check the updated README (section: output files) which discusses visualizing these loops in WashU genome browser. You can try both the latest and the legacy versions of WashU browser. Let us know if the problem is still not solved.

**Comment by jchap14** [comment]
Ahh yes it works nicely, not sure how I missed this before. Thanks for the quick response
