### ISSUE TITLE
/FitHiChIP/FitHiChIP_HiCPro.sh: line 841: [[: 0.01: syntax error: invalid arithmetic operator (error token is ".01")

### ISSUE THREAD

**Issue by YichaoOU** [ay-lab/FitHiChIP#82]
Hi,

I'm using the singularity container and got this warning/error? 

The program is running OK. Should I worry about it?

Thanks,
Yichao

**Comment by ay-lab** [comment]
Hi @YichaoOU 
Thanks for your query. Please do not use the singularity version. It's old. Please "git clone" the latest source code and use "FitHiChIP_HiCPro.sh" along with the configuration files provided.

**Comment by YichaoOU** [comment]
Thanks for the quick reply!

I'm trying to avoid installation. Is the docker version the latest?

Thanks,
Yichao

**Comment by souryacs** [comment]
Hi @YichaoOU 
The docker version is also outdated. Please use the "FitHiChIP_HiCPro.sh" file.

**Comment by ay-lab** [comment]
Hi @YichaoOU 
We have updated the Docker version in the latest release. Please check if it resolves the issue.
