### ISSUE TITLE
Syntax error when using Docker for executing FitHiChIP

### ISSUE THREAD

**Issue by Soh-hyon** [ay-lab/FitHiChIP#83]
Hi,

I have issues when using Docker for executing FitHiChIP.
The error message is exactly the same as the previous question asked by YichaoOU another user, but I'm already using Docker, not Singularity. Strangely, at FitHiChIP_HiCPro.sh line 841, there is annotation and even no "[[".
The program still runs despite the error, but there is no detected loop in output html file.

What can I do with this issue?

Thank you in advance!

 ================ Changing relative pathnames of the input files to their absolute path names =================
/
/FitHiChIP/FitHiChIP_HiCPro.sh: line 841: [[: 0.01: syntax error: invalid arithmetic operator (error token is ".01")
/FitHiChIP/FitHiChIP_HiCPro.sh: line 841: [[: 0.01: syntax error: invalid arithmetic operator (error token is ".01")
Executable of python (2): /root/miniconda2/bin//python
Executable of R : /usr/bin/Rscript

**Comment by souryacs** [comment]
Hi @Soh-hyon 
Thanks for your query. The Docker version is not updated. Please use the "FitHiChIP_HiCPro.sh" executable and install the required packages (as mentioned in the documentation).

**Comment by ay-lab** [comment]
Hi @Soh-hyon 
We have updated Docker version in the latest release. Please check if it resolves the issue.
