### ISSUE TITLE
FitHiChIP compatibility with the dm6 Drosophila melanogaster genome.

### ISSUE THREAD

**Issue by JosephAguilera** [ay-lab/FitHiChIP#84]
Hello!

I have a quick question regarding FitHiChIP's compatibility with the dm6 _Drosophila_ _melanogaster_ genome. 

I recently called the loops of my HiChIP samples and replicates, and serval hundred significant loops were successfully detected  on each chromosome. However, after the merging filter was applied, only the X chromosome loops were detected. In addition, this same phenomenon was seen when I utilized the "DiffAnalysisHiChIP.r" script. I only observed differential loops on the X chromosome. 

After observing the command line output after loop calling (inserted below), I noticed the merging filter seems to only be processing chromosomes 1-22 and chromosomes X and Y, which should run perfectly fine on the human and mouse genomes. But since the _Drosophila_ dm6 chromosome naming scheme is different (chrX, chrY, chr2L, chr2R, chr3L, chr3R),  I can see how only the X chromosome was detected. 

Do you think the _Drosophila_ chromosome names are the reason why the autosomal loops are not being included in the loop merging and differential loop functions? And if so, would you know of any potential work arounds? 

Thank you!

Best, 
Joseph

> ****** Merge filtering of adjacent loops is enabled *****
> ***** within function of merged filtering - printing the parameters ***
> *** bin_size:  5000
> *** headerInp:  1
> *** connectivity_rule:  8
> *** TopPctElem:  100
> *** NeighborHoodBinThr:  10000
> *** QValCol:  25
> *** PValCol:  24
> *** SortOrder:  0
> OutDir:  /Users/path/to/directory
> Processing the chromosome:  chr1
> Processing the chromosome:  chr2
> Processing the chromosome:  chr3
> Processing the chromosome:  chr4
> Processing the chromosome:  chr5
> Processing the chromosome:  chr6
> Processing the chromosome:  chr7
> Processing the chromosome:  chr8
> Processing the chromosome:  chr9
> Processing the chromosome:  chr10
> Processing the chromosome:  chr11
> Processing the chromosome:  chr12
> Processing the chromosome:  chr13
> Processing the chromosome:  chr14
> Processing the chromosome:  chr15
> Processing the chromosome:  chr16
> Processing the chromosome:  chr17
> Processing the chromosome:  chr18
> Processing the chromosome:  chr19
> Processing the chromosome:  chr20
> Processing the chromosome:  chr21
> Processing the chromosome:  chr22
> Processing the chromosome:  chrX
> No of nodes of G:  930
> No of edges of G:  590
> Number of connected components of G:  530
> Processing the chromosome:  chrY
> ==================== End of merge filtering adjacent interactions !!! ======================

**Comment by souryacs** [comment]
Hi @JosephAguilera 
Thanks for your query. Could you please check the following?
1) Are you using the latest code (or just git clone the latest code)? The merge filtering code was updated a long time ago to process different reference genomes.
2) Please check the chromosome size file, input interaction file, and the ChIP-seq peak file. They should contain the same chromosome information.
Please use the latest code and re-run your example, and let me know if you face any problems.

**Comment by souryacs** [comment]
Hi @JosephAguilera 
Please git clone the latest code and re-run your data, and let me know for any problems.

**Comment by JosephAguilera** [comment]
Hello @souryacs , 

I will try your suggestions and will let you know right after! I am pretty sure I am using the latest code but will double check. 

Thank you.

Best, 
Joseph

**Comment by JosephAguilera** [comment]
Hello @souryacs ,

I checked and I do have the latest version of FitHiChIP. Afterwards, I tried calling loops with the different methods available (e.g. Docker, HiC-Pro,Singularity) as I was previously only using docker. The loop calling and differential loop analysis worked perfectly after calling the HiChIP loops with FitHiChIP_HiCPro.sh instead of the FitHiChIP_Docker.sh script! Thank you for your help. 

Do you think the Docker script may have been missed in the latest update?

Best, 
Joseph

**Comment by souryacs** [comment]
Hi @JosephAguilera 
Glad to know that it worked. The docker and singularity versions are not updated, and we'll fix it soon. Please use FitHiChIP_HiCPro.sh until the update. Thanks.
