### ISSUE TITLE
Differential Analysis

### ISSUE THREAD

**Issue by jchap14** [ay-lab/FitHiChIP#9]
Hello,

I see that you have some scripts for differential analysis in this repo, but no description in the documentation. Is this something that is still in development?

Thanks,
James

**Comment by ay-lab** [comment]
Hi James, 
We have now integrated a basic version of differential HiChIP loop calling in the latest release (7.0). Please  check the updated documentation in https://ay-lab.github.io/FitHiChIP/, and in particular, documentation for differential analysis in https://ay-lab.github.io/FitHiChIP/usage/DiffLoops.html. Please notify for any queries.
