### ISSUE TITLE
Reference genome used for inferring peaks from HiChIP data

### ISSUE THREAD

**Issue by koushik20** [ay-lab/FitHiChIP#92]
Hi,

This is more of a question than an issue. Firstly thanks for the detailed documentation. I am using "inferring peaks from HiChIP" data functions and want to know if the reference genome used in the `-R` option is of hg19 or hg38. Because I generated the .ValidPairs, .DEPairs, .REPairs, and .SCPairs using hg19.

Thank you!

**Comment by ay-lab** [comment]
Hi @koushik20 
The -R option in your case should be "hg19". The parameter supports different reference genomes (hg19/hg38/mm9/mm10) depending on the valid pairs.

**Comment by koushik20** [comment]
Thanks for the response.
But the -R parameter is only considering hs, mm, ce, dm as options.
Shows an error when interpreting the "hg19" option.

**Comment by koushik20** [comment]
> Hi @koushik20 The -R option in your case should be "hg19". The parameter supports different reference genomes (hg19/hg38/mm9/mm10) depending on the valid pairs.

Thanks for the response.
But the -R parameter is only considering hs, mm, ce, dm as options.
Shows an error when interpreting the "hg19" option.

**Comment by ay-lab** [comment]
Hi @koushik20 
The "-R" parameter is same as the "-g" parameter in MACS2 (https://github.com/macs3-project/MACS/blob/master/docs/callpeak.md).
If the reference genome is "hg19 / hg38", please use "hs". If the reference genome is "mm9/mm10", use "mm".
