### ISSUE TITLE
Normalization of regions with focal copy number amplification 

### ISSUE THREAD

**Issue by dmuliaditan** [ay-lab/FitHiChIP#97]
Hello,

We are analyzing H3K27ac HiChIP data from cancer samples and we want to investigate how focal copy number amplifications affect H3K27ac mediated chromatin interactions in the affected genomic regions.  We understand that we need to consider these regions during normalization as they might lead to biases in the data. However, we also do not want to over-normalize as this might lead to actual biological events not being detected. We were therefore wondering how FitHiChIP consider focal CNV-affected regions during normalization? Also, do you have any advice on whether coverage or ICE bias correction is better for our case, or whether there are additional normalization steps needed prior to running FitHiChIP? Thank you!

Best regards,
Daniel

**Comment by ay-lab** [comment]
Hi Daniel,
Thanks for your query. Although we did not specifically test for such CNA regions, in our experience, coverage bias works much better than ICE normalization for HiChIP data. We confirmed such results for K562 cell line, a cancer cell line, so recommend to use the coverage bias. No additional normalization step is required.

**Comment by dmuliaditan** [comment]
Thank you for the explanation!

Best regards,
Daniel
