### ISSUE TITLE
Should input cool files be balanced/normalized?

### ISSUE THREAD

**Issue by nyuhic** [ay-lab/FitHiChIP#99]
Hello,

I am using cool/mcool files as input for calling loops. My cool files contain a 'weight' column which stores correction factors for different normalization methods. I was wondering if fithichip requires the cool file to be balanced or if it uses the 'weight' at all? I called loops on the same sample normalized with two different methods (and so having different correction factors in the weight column) and the results were almost identical. Should the input cool files be normalized/balanced or have a weight column for use with fithichip?

Thanks

**Comment by ay-lab** [comment]
Hi @nyuhic 
Thanks for your query. FitHiChIP does not use the "weight" factor but rather uses the raw contact counts. It then performs the coverage bias or ICE bias normalization (according to the --BiasType option provided in the configuration file). So, you do not need to provide the weight columns.

**Comment by nyuhic** [comment]
Thanks
